# Generated by Django 3.1.1 on 2020-09-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0003_remove_customuserprofile_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
