# Generated by Django 3.1.1 on 2020-09-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0005_auto_20200918_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='is_staff',
            field=models.BooleanField(default=True, verbose_name='is staff'),
        ),
    ]
