# Generated by Django 3.1.1 on 2020-09-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0006_customuserprofile_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='is staff'),
        ),
    ]
