# Generated by Django 3.1.1 on 2020-09-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_profile', '0007_auto_20200918_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Bio'),
        ),
    ]
