# Generated by Django 3.1.1 on 2020-09-19 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_courses', '0002_auto_20200919_1040'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_courses.course', verbose_name='course')),
            ],
        ),
    ]
