# Generated by Django 3.1.1 on 2020-09-18 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('author', models.CharField(max_length=50, verbose_name='author')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/', verbose_name='thumbnail')),
                ('added_on', models.DateField(auto_now_add=True, verbose_name='added on')),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='course')),
            ],
        ),
    ]
