# Generated by Django 3.1.1 on 2020-09-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_courses', '0002_auto_20200919_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True, verbose_name='video or playlist link'),
        ),
    ]
